### ISSUE TITLE
Add basic toolbar

### ISSUE THREAD

**Issue by alexandreruban** [alexandreruban/action-markdown#8]
Just like for the real GitHub issue editor, `ActionMarkdown` should have a basic toolbar to create:

- Title
- Bold text
- Italic text
- Quotes
- Code snippets
- Unordered lists 
- Ordered lists

Bonus if there's a keyboard shortcut attached.

**Comment by brunoprietog** [comment]
[@github/markdown-toolbar-element](https://github.com/github/markdown-toolbar-element) is very accessible and a great option.

**Comment by alexandreruban** [comment]
Thanks for pointing this out to me! This is exactly what I was looking for!! 😍
